#%RAML 1.0
---
title: askMe survey API
baseUri: https://askme-scai.firebaseapp.com/
version: v1

/survey/list:
  get:
    description: survey list
    queryParameters:
      search:
        displayName: search text
        type: string
        description: full text search
        required: false
      active:
        displayName: active survey
        type: bool
        description: filter over active surveys
        required: false
      first:
        displayName: first visible record (for pagination)
        type: int
        description: first visible record (for pagination)
        required: false
        default: 0
      count:
        displayName: number of visible records (for pagination)
        type: int
        description: number of visible records (for pagination)
        required: false
        default: 20
    responses:
      200:
        body:
          application/json:
            example: |
                [
                  {
                    "id": 125866427,
                    "active": true,
                    "name": "Survey fancy smart",
                    "description": "Description for Survey fancy smart",
                    "numberOfQuestions": 3
                  },
                  {
                    "id": 604064560,
                    "active": true,
                    "name": "Survey smart vision",
                    "description": "Description for Survey smart vision",
                    "numberOfQuestions": 2
                  }
                ]